### ISSUE TITLE
[0.5pt] Setup Kanban

### ISSUE THREAD

**Issue by Hannziegel** [Hannziegel/rails-food-recipes#19]
## Kanban Board
 - [Repository Link](https://github.com/Hannziegel/rails-food-recipes)
 - [Project Kanban board Link](https://github.com/users/Hannziegel/projects/1/views/1)
 
 ### Authors:
- Rodrigo Johann Reckziegel Nunes https://github.com/Hannziegel/rails-food-recipes/issues/12
- Karla Valentina Delgado https://github.com/Hannziegel/rails-food-recipes/issues/16
- Karam Fouad  https://github.com/Hannziegel/rails-food-recipes/issues/13

**Comment by prolajumokeoni** [comment]
Hi @Hannziegel @karlavdelgadof, you are a team of three kindly update the issue description with information about the number of people in your group

**Comment by HAMMAS-SALEEM** [comment]
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @Hannziegel, @karlavdelgadof :wave:

## Highlights :1st_place_medal:

✔️ Descriptive Issue Title
✔️ Descriptive Issue Summary
✔️ Using Github Project Feature
✔️ Following some requirements

Good job on implementing some of the reqirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**[Optional]**

![Capture](https://user-images.githubusercontent.com/93039359/203126376-1540ee9d-d750-4c34-bec8-8d2e795b41e1.PNG)

- [x] You can see that you have not assigned that card shown in the image above ⬆️ Kindly assign that to follow the requirements 👍

**Comment by tufoinnkuo10** [comment]
## Status: Approved :heavy_check_mark:

Hi @TEAM

Your project is complete! Great job for making the changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Board well fixed

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/ToMjGpvEPoYYu7Hzsys/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
